INSERT INTO CATEGORIAS(cat_id,cat_nome) VALUES (1,'FICÇÃO LITERÁRIA');
INSERT INTO CATEGORIAS(cat_id,cat_nome) VALUES (2,'NÃO-FICÇÃO');
INSERT INTO CATEGORIAS(cat_id,cat_nome) VALUES (3,'SUSPENSE');
INSERT INTO CATEGORIAS(cat_id,cat_nome) VALUES (4,'POESIA');
INSERT INTO CATEGORIAS(cat_id,cat_nome) VALUES (5,'FICÇÃO CIENTÍFICA');
INSERT INTO CATEGORIAS(cat_id,cat_nome) VALUES (6,'HORROR');
INSERT INTO CATEGORIAS(cat_id,cat_nome) VALUES (7,'FANTASIA');
INSERT INTO CATEGORIAS(cat_id,cat_nome) VALUES (8,'ROMANCE');



